#服务端口
server:
  port: 8078


# shiro 配置
# 启用基本身份认证
security:
  basic:
    enabled: false
# 禁用安全管理策略
management:
  security:
    enabled: false

#LOG
logging:
  level:
    org:
      springframework:
        web: INFO                    #日志级别
  file: D:/logs/zhongka-${sys.env}/${spring.application.name}.log  #日志地址

# 前端页面基本配置

front:
  freemarker:
    # ftl文件夹路径
    ftl-files-path: D:\\My_Document\\zhongka-code\\ZK-AiO\\biz-erp\\front\\views
    # css,js,静态资源路径
    static-files-path: D:\\My_Document\\zhongka-code\\ZK-AiO\\biz-erp\\front\\public



# freemarker 基本配置
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
    order: 1
    # 设定ftl文件路径
    template-loader-path: file:/${front.freemarker.ftl-files-path}
  resources:
    # 设定静态文件路径，js,css等
    static-locations: file:/${front.freemarker.static-files-path}
  #DATASOURCE
  datasource:
    url: jdbc\:mysql\://localhost\:3306/new_erp?useUnicode\=true&characterEncoding\=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#redis
  redis:
    host: 127.0.0.1
    password:
    pool:
      max-active: 8
    maxIdle: 100
    maxWaitMillis: -1
    minIdle: 10
    port: 6379
    timeout: 0
  session:
    store-type: redis

#MYBATIS 基本配置
mybatis:
  type-aliases-package: com.cs.*.model
  mapper-locations: classpath*:/com/cs/*/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

#c3p0数据源配置
c3p0:
  jdbcUrl: jdbc\:mysql\://localhost\:3306/new_erp?useUnicode\=true&characterEncoding\=UTF-8
  user: root
  password: 123456
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
